% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  14pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Statistical Inference in a Cocaine Drug Bust},
  pdfauthor={David Fakolujo, Akinyemi Apampa, Ravin Jayasuriya, Prince Oloma and Joshua Ogunbo},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{\textbf{Statistical Inference in a Cocaine Drug Bust}}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{DATA 602, Winter 2025}
\author{David Fakolujo, Akinyemi Apampa, Ravin Jayasuriya, Prince Oloma
and Joshua Ogunbo}
\date{}

\begin{document}
\maketitle

\subsection{\texorpdfstring{\textbf{Background}}{Background}}\label{background}

A cocaine bust in Calgary yielded \textbf{N₁ = 496} suspected cocaine
plastic packets. To convict the suspected drug traffickers, the
\textbf{Alberta Crown Prosecution Service (ACPS)} and the
\textbf{Calgary Police Service (CPS)} had to prove that there was
\textbf{genuine cocaine} in (at least one of) the packets.

Apparently, drug traffickers have been \textbf{mixing ``clean'' packets}
(i.e., packets that are negative for cocaine, often containing corn
starch) with \textbf{``dirty'' packets} (i.e., packets that are positive
for cocaine) to confound the police.

Due to \textbf{budget limitations} or a \textbf{lack of resources}, law
enforcement is often restricted to testing \textbf{a smaller sample} of
the total shipment. This raises the question:

\begin{quote}
\emph{How can statistical inference be used to estimate the number of
contaminated packets with minimal testing?}
\end{quote}

By analyzing this problem using \textbf{statistical methods}, we aim to
demonstrate how \textbf{statistical inference can be utilized in law
enforcement} to assist in decision-making.

The goal of this project is to develop a \textbf{statistical inference
method} to determine the \textbf{total number of contaminated packets}
within a cocaine shipment. This estimation is crucial for \textbf{legal
proceedings}, as it determines whether there is \textbf{sufficient
evidence} for conviction.

\subsection{\texorpdfstring{\textbf{Methods}}{Methods}}\label{methods}

To estimate \textbf{\(\theta\)}, the total number of contaminated
packets, we will use the following statistical methods:

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  \textbf{Hypergeometric Distribution:} Models the probability of
  selecting \textbf{dirty packets} in a \textbf{limited sample} without
  replacement.
\end{enumerate}

\[
P_{\theta}(X_1 = x_1) = \frac{\binom{\theta}{x_1} \binom{N_1 - \theta}{n_1 - x_1}}{\binom{N_1}{n_1}}
\] ~\\
\strut \\
\strut \\
where:

\begin{itemize}
\tightlist
\item
  \(N_1\) - The total number of packets,
\item
  \(n_1\) - The sample size,
\item
  \(\theta\) is the unknown number of dirty packets,
\item
  \(x_1\) represents the observed number of dirty packets,
\item
  \(N_1 - \theta\) is the number of clean packets in the population,
\item
  \(n_1 - x_1\) is the number of clean packets from the sample.\\
\end{itemize}

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Maximum Likelihood Estimation (MLE):} This was used to
  determine the total number of dirty packets,\textbf{\(\theta\)}, in
  the parameter space containing all the possible values of
  \textbf{\(\theta\)}, which has the highest probability in the
  hypergeometric distribution and negative hypergeometric distribution
\end{enumerate}

\[
\hat{\theta}_1 = \underset{\theta \in \Theta(x_1)}{\arg\max} P_{\theta}(X_1 = x_1).
\]

\hfill\break
\hfill\break
\hfill\break

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  \textbf{Monte Carlo Simulation}: Monte Carlo simulation was used to
  evaluate and compare the performance of the two estimation approaches
  by repeatedly generating synthetic data and applying the estimation
  methods. The process involved the following steps:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  \textbf{Hypergeometric Distribution:}

  \begin{itemize}
  \tightlist
  \item
    Generated \textbf{\(N\)} random samples of dirty packets based on
    the observed sample size.\\
  \item
    Applied the \textbf{hypergeometric function} to each sample to
    estimate the \textbf{maximum likelihood estimate (MLE)} of the total
    number of contaminated packets (\(\theta\)) across various sample
    sizes.
  \end{itemize}
\item
  \textbf{Negative Hypergeometric Distribution:}

  \begin{itemize}
  \tightlist
  \item
    Similarly, generated \textbf{\(N\)} random samples of dirty packets
    under a \textbf{negative hypergeometric} framework.\\
  \item
    Applied the \textbf{negative hypergeometric function} to estimate
    \(\theta\) for each generated sample using MLE.
  \end{itemize}
\end{itemize}

These simulations provided insights into the \textbf{bias, variance, and
accuracy} of the estimation methods, ensuring that the chosen approach
performs well under repeated sampling conditions.

\subsection{\texorpdfstring{\textbf{Analysis and Results
}}{Analysis and Results }}\label{analysis-and-results}

\subsubsection{Scenario 1}\label{scenario-1}

Our analysis involves taking a fixed sample of size \(n = 2\) from a
population of \(N = 496\). We then evaluate different cases where the
number of dirty packets in the sample, \(x_1\), can take values from
\(\{0,1,2\}\).

Using Maximum Likelihood Estimation (MLE), we compute the likelihood
function for all values of \(\theta\), and identify the value of
\(\theta\) that maximizes the likelihood.

\subsubsection{\texorpdfstring{\textbf{Case 1: Estimating} \(\theta\)
When
\(X_1 = 1\)}{Case 1: Estimating \textbackslash theta When X\_1 = 1}}\label{case-1-estimating-theta-when-x_1-1}

\includegraphics{report_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{verbatim}
## [1] "The maximum likelihood estimate for theta is: 248"
\end{verbatim}

\begin{verbatim}
## [1] "The maximum probability is: 0.501010101010101"
\end{verbatim}

From the output, the \textbf{Maximum Likelihood Estimate (MLE)}
indicates that the most likely number of dirty packets in the population
is \(\theta = 248\).

This means that, given a sample of \textbf{2 packets}, where \textbf{1
was found to be dirty}, the best estimate for the total number of dirty
packets in the entire population is \textbf{248}.

Additionally, the \textbf{likelihood} of observing exactly \textbf{1
dirty packet} in the sample, assuming that \(\theta = 248\), is
approximately \textbf{50.1\%}.

\subsubsection{\texorpdfstring{Case 2: Estimating \(\theta\) When
\(X_1 = 0\)}{Case 2: Estimating \textbackslash theta When X\_1 = 0}}\label{case-2-estimating-theta-when-x_1-0}

\includegraphics{report_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{verbatim}
## [1] "The maximum likelihood estimate for theta is: 0"
\end{verbatim}

\begin{verbatim}
## [1] "The maximum probability is: 1"
\end{verbatim}

\hfill\break

When no dirty packets (\(x_1 = 0\)) are observed in the sample, the
\textbf{Maximum Likelihood Estimate (MLE)} suggests that the most likely
value of \(\theta\) (the total number of dirty packets in the
population) is \textbf{0}.

This conclusion makes intuitive sense if none of the selected packets
tested positive for cocaine, the best estimate is that there are
\textbf{no dirty packets} in the entire population. In other words,
based on the sample data, it is most probable that all packets in the
population are clean.

Mathematically, this means that the \textbf{likelihood function} reaches
its highest value when \(\theta = 0\), reinforcing the idea that the
absence of dirty packets in the sample strongly suggests their absence
in the entire population.

\subsubsection{\texorpdfstring{Case 3: Estimating \(\theta\) When
\(X_1 = 2\)}{Case 3: Estimating \textbackslash theta When X\_1 = 2}}\label{case-3-estimating-theta-when-x_1-2}

\includegraphics{report_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{verbatim}
## [1] "The maximum likelihood estimate for theta is: 496"
\end{verbatim}

\begin{verbatim}
## [1] "The maximum probability is: 1"
\end{verbatim}

\hfill\break
When two dirty packets (\(x_1 = 2\)) are observed in the sample, the
\textbf{Maximum Likelihood Estimate (MLE)} suggests that the most likely
value of \(\theta\) (the total number of dirty packets in the
population) is \textbf{496}.

This conclusion makes intuitive sense if two of the selected packets
tested positive for cocaine, the best estimate is that there are
\textbf{496 dirty packets} in the entire population. In other words,
based on the sample data, it is most probable that all packets in the
population are dirty

Mathematically, this means that the \textbf{likelihood function} reaches
its highest value when \(\theta = 496\), reinforcing the idea that the
presence of dirty packets in the sample strongly suggests their prsence
in the entire population.

\hfill\break

\subsection{Scenario 2}\label{scenario-2}

We analyzed the joint sampling distribution of two dependent discrete
random variables, \(X_1\) and \(X_2\), representing the number of dirty
packets found in two successive rounds of random sampling without
replacement. Initially, \(n_1 = 2\) packets were tested from a total of
\(N_1 = 496\), and both were found clean. Subsequently, the
investigators selected \(n_2 = 4\) additional packets from the remaining
\(N_2 = 494\) packets, hoping to detect at least one dirty packet to
support their case.

After the initial test of \(n_1 = 2\) packets resulted in \(X_1 = 0\)
dirty packets, additional \(n_2 = 4\) packets were tested to gather
sufficient evidence. Let \(X_2\) represent the number of dirty packets
in this second sample.

\subsubsection{\texorpdfstring{Joint Probability of \(X_1\) and
\(X_2\)}{Joint Probability of X\_1 and X\_2}}\label{joint-probability-of-x_1-and-x_2}

The joint probability function is given by:

\[
P_{\theta}(X_1 = x_1, X_2 = x_2) = P_{\theta}(X_2 = x_2 | X_1 = x_1) P_{\theta}(X_1 = x_1)
\]

Given that:

\begin{itemize}
\tightlist
\item
  \(X_1 \sim \text{Hypergeometric}(N_1 = 496, \theta, n_1 = 2)\),
\item
  \(X_2 | X_1 = x_1 \sim \text{Hypergeometric}(N_2 = 496 - 2, \theta - x_1, n_2 = 4)\),
\end{itemize}

we define the possible values of \(\theta\).

\includegraphics{report_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{verbatim}
## [1] "The Maximum Likelihood Estimate for theta is: 247"
\end{verbatim}

\begin{verbatim}
## [1] "The maximum Probability is: 0.376525945724873"
\end{verbatim}

\begin{verbatim}
## [1] "The smallest possible value of theta for the joint sampling distribution is: 2"
\end{verbatim}

\begin{verbatim}
## [1] "The largest possible value of theta for the joint sampling distribution is: 492"
\end{verbatim}

\subsection{Scenario 3}\label{scenario-3}

Given that \(x_2 = 2\) out of the additional \(n_2 = 4\) sampled packets
were found to be dirty, the conviction of the accused is now certain.
However, the total number of dirty packets, \(\theta\), remains unknown
and needs to be estimated. \(\newline\) \#\# Maximum Likelihood
Estimation (MLE)\\
\(\newline\) We determine \(\theta\), the \textbf{maximum likelihood
estimate (MLE)} by maximizing the joint probability
\(P_{\theta}(X_1 = x_1, X_2 = x_2)\) as a function of \(\theta\) over
its feasible parameter space, \(\Theta(x_1, x_2)\), which depends on the
observed values \(x_1\) and \(x_2\). Since both \(X_1(\theta)\) and
\(X_2(\theta)\) are functions of \(\theta\), the possible values of
\(\theta\) must be considered. \#\# Finding the MLE We obtain The MLE,
denoted as \(\hat{\theta}_2\), by evaluating
\(P_{\theta}(X_1 = 0, X_2 = 2)\) for all possible values of \(\theta\)
in \(\Theta(0,2)\) and selecting the value that maximizes this
probability. This approach ensures that the estimated \(\theta\) is the
most likely given the observed data.

With \(x_2 = 2\) dirty packets found in the second test, the conviction
is certain, but the actual number of dirty packets remains unknown. To
estimate \(\theta\), we maximize the joint probability function:

\[
\hat{\theta}_2 = \underset{\theta \in \Theta(0,2)}{\arg\max} P_{\theta}(X_1 = 0, X_2 = 2)
\]

The new parameter space \(\Theta(0,2)\) depends on the observed values
of \(X_1\) and \(X_2\).

\includegraphics{report_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{verbatim}
## [1] "The Maximum Likelihood Estimate for theta (joint) is: 165"
\end{verbatim}

\begin{verbatim}
## [1] "The maximum Probability for joint distribution is: 0.1324900852217"
\end{verbatim}

\hfill\break

\subsection{Scenario 4}\label{scenario-4}

After analyzing the packets, where some packets were identified as
``dirty,'' we estimated the total number of dirty packets (\(\theta\))
in a set of 496 packets. Two different approaches can be used for this
estimation:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Fixed Sample Method}: Drawing a fixed number of packets at
  random and analyzing them.
\item
  \textbf{Sequential Sampling Method}: Drawing packets one by one until
  the first dirty packet is found.
\end{enumerate}

Using statistical inference techniques, we compared these two estimation
methods by evaluating their \textbf{bias} and \textbf{root mean squared
error (RMSE)} through a \textbf{Monte Carlo simulation}.

\hfill\break

\includegraphics{report_files/figure-latex/unnamed-chunk-6-1.pdf}
\includegraphics{report_files/figure-latex/unnamed-chunk-6-2.pdf}
\includegraphics{report_files/figure-latex/unnamed-chunk-6-3.pdf}

\subsection{\texorpdfstring{\textbf{Comparison of MLE1 and
MLE3}}{Comparison of MLE1 and MLE3}}\label{comparison-of-mle1-and-mle3}

In this study, we compared two different Maximum Likelihood Estimators
(MLEs) for \(\theta\):\\
1. \textbf{MLE1 (Fixed-\(n\) Estimate)}, where the sample size \(n\) is
pre-determined.\\
2. \textbf{MLE3 (Sequential-\(n\) Estimate)}, where sampling continues
until at least one dirty packet is found.

\subsubsection{\texorpdfstring{\textbf{Comparison
Metrics}}{Comparison Metrics}}\label{comparison-metrics}

\begin{itemize}
\tightlist
\item
  \textbf{Bias:} Measures the accuracy of the estimator. A lower bias
  means the estimator is closer to the true \(\theta\).\\
\item
  \textbf{RMSE (Root Mean Square Error):} Accounts for both accuracy and
  variability. A lower RMSE means the estimator is more stable and
  reliable.
\end{itemize}

\subsection{\texorpdfstring{\textbf{Conclusion from Our
Analysis}}{Conclusion from Our Analysis}}\label{conclusion-from-our-analysis}

\subsubsection{\texorpdfstring{\textbf{Bias}}{Bias}}\label{bias}

\begin{itemize}
\tightlist
\item
  \textbf{MLE1 remains unbiased} across all values of \(\theta\),
  meaning it provides an accurate estimate of the true number of dirty
  packets.\\
\item
  \textbf{MLE3 is accurate when \(\theta\) is small}, but \textbf{starts
  to overestimate significantly} when \(\theta\) is large.
\end{itemize}

\subsubsection{\texorpdfstring{\textbf{RMSE}}{RMSE}}\label{rmse}

\begin{itemize}
\tightlist
\item
  \textbf{MLE1 has a lower and more stable RMSE}, meaning it
  consistently produces precise estimates.\\
\item
  \textbf{MLE3 has a low RMSE when \(\theta\) is small}, but \textbf{its
  RMSE increases when \(\theta\) is large}, indicating higher
  variability and inconsistency.
\end{itemize}

\subsection{\texorpdfstring{\textbf{Key
Findings}}{Key Findings}}\label{key-findings}

\begin{itemize}
\tightlist
\item
  \textbf{MLE3 performs well when \(\theta\) is low}, as it
  \textbf{efficiently detects contamination without excessive sampling}.
  This makes it useful in \textbf{resource-constrained settings} where
  testing capacity is limited.\\
\item
  \textbf{MLE3 becomes unreliable when \(\theta\) is high}, as it
  \textbf{overestimates the number of contaminated packets}, leading to
  potential \textbf{false conclusions in forensic settings}.\\
\item
  \textbf{MLE1 remains stable across all values of \(\theta\)},
  providing \textbf{consistent and dependable estimates}, making it a
  \textbf{preferred estimator when precision is critical}.
\end{itemize}

In a forensic or legal setting, where \textbf{accurate estimation of
contamination levels is crucial}, a judge would likely prefer
\textbf{MLE1} due to its \textbf{stability and lack of overestimation
bias}. While \textbf{MLE3 can be useful for early detection} when
contamination is rare, its tendency to \textbf{overestimate high
contamination cases makes it unreliable for critical decision-making}.

Thus, \textbf{MLE1 is the recommended estimator for legal
investigations} to ensure accurate and fair conclusions.

\subsection{\texorpdfstring{\textbf{Group Members'
Contributions}}{Group Members' Contributions}}\label{group-members-contributions}

\begin{itemize}
\tightlist
\item
  \textbf{Akin} - Answered part E (S4). Prepared results section of the
  report.\\
\item
  \textbf{David} - Answered question C and D. Prepared methods section
  of the report.\\
\item
  \textbf{Joshua} - Answered part E (S3). Prepared results section of
  the report.\\
\item
  \textbf{Prince} - Answered part E (S2). Prepared conclusion section of
  the report.\\
\item
  \textbf{Ravin} - Answered A and B of the problem. Prepared background
  section of the report.
\end{itemize}

\subsection{Reference}\label{reference}

Shuster, J. J. (1991). The statistician in a reverse cocaine sting. The
American Statistician, 45(2), 123--124

\end{document}
